import type { ApiPair, ApiSignal } from "@/types/tradeApi";
import type { Signal, SignalReasoning, SignalStatus, Timeframe, TradingPair } from "@/types/signal";

const timeframeFallback: Timeframe = "1h";
const supportedTimeframes = new Set<Timeframe>(["1m", "5m", "15m", "30m", "1h", "4h", "1d"]);

function parsePrice(value: string | null): number | null {
  if (value === null) {
    return null;
  }

  const parsed = Number(value);
  return Number.isFinite(parsed) ? parsed : null;
}

function normalizeTimeframe(value: string): Timeframe {
  return supportedTimeframes.has(value as Timeframe) ? (value as Timeframe) : timeframeFallback;
}

function deriveStatus(signal: ApiSignal): SignalStatus {
  if (signal.expires_at && new Date(signal.expires_at).getTime() < Date.now()) {
    return "expired";
  }

  return signal.direction === "neutral" ? "watchlist" : "active";
}

function computeRiskReward(signal: ApiSignal): number | null {
  const entry = parsePrice(signal.entry_price);
  const stopLoss = parsePrice(signal.stop_loss);
  const takeProfit = parsePrice(signal.take_profit);

  if (entry === null || stopLoss === null || takeProfit === null || entry === stopLoss) {
    return null;
  }

  const risk = Math.abs(entry - stopLoss);
  const reward = Math.abs(takeProfit - entry);

  if (risk === 0) {
    return null;
  }

  return reward / risk;
}

function buildReasoning(signal: ApiSignal): SignalReasoning {
  const thesis = signal.rationale ?? "The backend returned this signal without a written rationale.";
  const indicators = signal.indicators_snapshot;
  const indicatorNames = indicators ? Object.keys(indicators).slice(0, 4) : [];

  return {
    thesis,
    confirmations:
      indicatorNames.length > 0
        ? indicatorNames.map((name) => `${name} was included in the model context.`)
        : ["Indicator details were not included with this signal."],
    riskPlan:
      signal.stop_loss !== null
        ? "Manage risk against the supplied stop loss and reassess if market structure changes."
        : "No stop loss was supplied, so this signal should stay in review mode before execution.",
    invalidation:
      signal.stop_loss !== null
        ? "The setup is invalidated if price accepts beyond the stop-loss level."
        : "Wait for a directional plan with explicit invalidation before acting.",
    executionNotes: [
      signal.ai_provider && signal.ai_model
        ? `Generated by ${signal.ai_provider}/${signal.ai_model}.`
        : "AI provider metadata was not supplied.",
      "Use fresh market context before placing real capital at risk."
    ]
  };
}

export function mapApiPair(pair: ApiPair): TradingPair {
  return {
    id: pair.id,
    symbol: pair.symbol,
    baseCurrency: pair.base_currency,
    quoteCurrency: pair.quote_currency,
    displayName: pair.display_name ?? `${pair.base_currency} / ${pair.quote_currency}`,
    isActive: pair.is_active
  };
}

export function mapApiSignal(signal: ApiSignal, pairs: TradingPair[]): Signal {
  const symbol = signal.pair_symbol ?? pairs.find((pair) => pair.id === signal.pair_id)?.symbol ?? "UNKNOWN";
  const pair = pairs.find((item) => item.symbol === symbol);
  const takeProfit = parsePrice(signal.take_profit);

  return {
    id: signal.id,
    pairId: signal.pair_id,
    symbol,
    displayName: pair?.displayName ?? symbol,
    direction: signal.direction,
    status: deriveStatus(signal),
    confidence: signal.confidence,
    entryPrice: parsePrice(signal.entry_price) ?? 0,
    stopLoss: parsePrice(signal.stop_loss),
    targets: takeProfit === null ? [] : [{ label: "TP1", price: takeProfit }],
    timeframe: normalizeTimeframe(signal.timeframe),
    generatedAt: signal.generated_at,
    expiresAt: signal.expires_at,
    riskReward: computeRiskReward(signal),
    rationale: signal.rationale ?? "No rationale was supplied for this signal.",
    reasoning: buildReasoning(signal)
  };
}
